fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "inifile": "git://github.com/cprice-puppet/puppetlabs-inifile"
    "keystone": "git://github.com/stackforge/puppet-keystone.git"
    "nova": "git://github.com/stackforge/puppet-nova.git"
  symlinks:
    "ceilometer": "#{source_dir}"
